[env]
TERM = "alacritty"

[font]
normal.family = "MesloLGS Nerd Font Mono"
offset = { x = 0, y = 5 }
glyph_offset = { x = 0, y = 4 }
size = 14

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_light.toml"
]
live_config_reload = true

[colors.primary]
background = '#f2e5bc'

[colors.normal]
black = '#3c3836'

[colors.bright]
black = '#7c6f64'

[[hints.enabled]]
regex = "https://[^\\s}>\\)]+"
hyperlinks = true
post_processing = true
command = { program = "open" }
mouse = { enabled = true, mods = "Command" }

[[hints.enabled]]
regex = "fb-vscode://[^\\s]+"
hyperlinks = true
post_processing = false
command = { program = "open" }
mouse = { enabled = true, mods = "Shift" }

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen"},
  { key = "Back", mods = "Command", chars = "\u001b[3;9~"},
  { key = "K", mods = "Command", chars = "\u001bk"}
]

[selection]
save_to_clipboard = true

[window]
blur = true
decorations = "Buttonless"
dimensions = { columns = 200, lines = 50 }
dynamic_padding = true
opacity = 0.95
option_as_alt = "Both"
padding = { x = 10, y = 10 }
