bold_font auto
bold_italic_font auto
font_family MesloLGS Nerd Font Mono
font_size 14
italic_font auto

copy_on_select clipboard
confirm_os_window_close 0
macos_option_as_alt no
modify_font cell_height 115%
single_window_margin_width 0
window_border_width 3pt
window_margin_width 5
window_padding_width 5
enabled_layouts Tall, *

map cmd+backspace send_text all \x1b[3;9~
map cmd+k send_text all \x1bk
map f1 new_window_with_cwd
map kitty_mod+m toggle_layout stack
map cmd+shift+enter toggle_layout stack
map cmd+w close_window
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

# BEGIN_KITTY_THEME
# Solarized Dark
include current-theme.conf
# END_KITTY_THEME

include overrides.conf
